version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend-app
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - NODE_ENV=development

  frontend:
    build: ./frontend
    container_name: frontend-app
    ports:
      - "3000:80"
    depends_on:
      - backend
